name: AWS Deployment
on:
  push:
    branches:
      - main
env:
  HANDLER_NAME: lambda_function
  FUNCTION_NAME: vultrCostGetter

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    name: Build and deploy lambda function
    steps:
      # Use versioned actions
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Zip files and update function
        run: |
          zip "${{env.HANDLER_NAME}}.zip" "${{env.HANDLER_NAME}}.py" constants.py
          aws lambda update-function-code --function-name "${{env.FUNCTION_NAME}}" \
          --zip-file "fileb://${{env.HANDLER_NAME}}.zip"
